### PR TITLE
First PR 

### PR DESCRIPTION
**Pull request by mythrisurabhi**
This is my first PR

### CODE REVIEW

**Review by Qiaodan007 — COMMENTED** [review]
for app.py, please make sure remove the endpoint_url and the aws access keys

**Review by Qiaodan007 — COMMENTED** [review]
don't need to include the env.json file if it is for local testing right?

**Review by Qiaodan007 — COMMENTED** [review]
in your template.yaml, the region name can be referenced by !ref

**Comment by mythrisurabhi** [comment]
updated sam template with parameters removed the endpoint URL and access key values from a serverless function and deleted the env.json file.

**Pull request merged**
